input:
  type: mag

predictors:
  similarity:
    enabled: true
    tool: diamond
  domains:
    enabled: true
  operons:
    enabled: true
  pathway:
    enabled: true
    crossfeeding: true

quality:
  completeness:
    profile: auto
  coherence:
    process: true
    pathway: true
    complex: true
  consistency:
    taxonConstraints: true
