package gspa.metrics

import gspa.model.QualityReport
import gspa.model.ConsistencyViolation
import org.slf4j.Logger
import org.slf4j.LoggerFactory

/**
 * Generates self-contained HTML quality reports.
 * No external dependencies — all CSS/JS is inline.
 */
class HtmlReportWriter {

    private static final Logger log = LoggerFactory.getLogger(HtmlReportWriter)

    static void writeHtml(QualityReport report, File output) {
        output.text = generateHtml(report)
        log.info("HTML report written to: ${output}")
    }

    static void writeMultiGenomeHtml(List<QualityReport> reports, File output) {
        output.text = generateMultiHtml(reports)
        log.info("Multi-genome HTML report written to: ${output}")
    }

    private static String generateHtml(QualityReport report) {
        def violations = report.violations ?: []
        def missingEF = report.missingEssentialFunctions ?: []
        def presentEF = report.presentEssentialFunctions ?: []

        """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>GSPA Quality Report - ${esc(report.genomeId)}</title>
<style>
${css()}
</style>
</head>
<body>
<div class="container">
<h1>GSPA Quality Report</h1>
<p class="subtitle">Genome: <strong>${esc(report.genomeId)}</strong> | Date: ${esc(report.assessmentDate ?: 'N/A')}</p>

<div class="summary-grid">
  ${scoreCard('Completeness', report.completeness, 'essential functions present')}
  ${scoreCard('Process Coherence', report.processCoherence, 'has_part dependencies satisfied')}
  ${scoreCard('Pathway Coherence', report.pathwayCoherence, 'triggered pathways complete')}
  ${scoreCard('Complex Coherence', report.complexCoherence, 'protein complexes coherent')}
  ${scoreCard('Composite Score', report.compositeScore, 'weighted overall quality')}
  <div class="card ${report.consistent ? 'good' : 'bad'}">
    <div class="card-value">${report.consistent ? 'PASS' : 'FAIL'}</div>
    <div class="card-label">Consistency</div>
    <div class="card-detail">${violations.size()} violations</div>
  </div>
</div>

<h2>Annotation Summary</h2>
<table>
<tr><th>Metric</th><th>Value</th></tr>
<tr><td>Total proteins</td><td>${report.totalProteinCount}</td></tr>
<tr><td>Annotated proteins</td><td>${report.annotatedProteinCount}</td></tr>
<tr><td>Annotation coverage</td><td>${pct(report.annotationCoverage)}</td></tr>
<tr><td>Mean Information Content</td><td>${fmt2(report.meanIC)}</td></tr>
</table>

${report.annotationCountBySource ? """
<h2>Annotations by Source</h2>
<table>
<tr><th>Source</th><th>Count</th></tr>
${report.annotationCountBySource.collect { src, cnt -> "<tr><td>${esc(src)}</td><td>${cnt}</td></tr>" }.join('\n')}
</table>
""" : ''}

<h2>Essential Functions</h2>
<p>${presentEF.size()} of ${presentEF.size() + missingEF.size()} essential functions present (${pct(report.completeness)})</p>

${missingEF ? """
<h3>Missing Essential Functions</h3>
<table>
<tr><th>GO Term</th></tr>
${missingEF.sort().collect { "<tr><td>${esc(it)}</td></tr>" }.join('\n')}
</table>
""" : '<p class="ok">All essential functions present.</p>'}

${violations ? """
<h2>Consistency Violations</h2>
<table>
<tr><th>Type</th><th>Severity</th><th>Description</th><th>GO Terms</th><th>Proteins</th></tr>
${violations.collect { v -> """<tr>
<td>${esc(v.type.toString())}</td>
<td class="${v.severity == ConsistencyViolation.Severity.ERROR ? 'bad' : 'warn'}">${esc(v.severity.toString())}</td>
<td>${esc(v.description)}</td>
<td>${esc(v.involvedGoTerms?.join(', ') ?: '')}</td>
<td>${esc(v.involvedProteins?.join(', ') ?: '')}</td>
</tr>"""}.join('\n')}
</table>
""" : ''}

<footer>Generated by GSPA (Genome-Scale Protein Annotation) v0.1.0</footer>
</div>
</body>
</html>"""
    }

    private static String generateMultiHtml(List<QualityReport> reports) {
        """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>GSPA Quality Comparison</title>
<style>
${css()}
</style>
</head>
<body>
<div class="container">
<h1>GSPA Quality Comparison</h1>
<p class="subtitle">${reports.size()} genomes compared</p>

<table>
<tr>
  <th>Genome</th><th>Proteins</th><th>Coverage</th>
  <th>Completeness</th><th>Process Coh.</th><th>Pathway Coh.</th>
  <th>Complex Coh.</th><th>Consistent</th><th>Mean IC</th><th>Composite</th>
</tr>
${reports.collect { r -> """<tr>
  <td>${esc(r.genomeId)}</td>
  <td>${r.totalProteinCount}</td>
  <td>${pct(r.annotationCoverage)}</td>
  <td class="${colorClass(r.completeness)}">${pct(r.completeness)}</td>
  <td class="${colorClass(r.processCoherence)}">${r.processCoherence >= 0 ? pct(r.processCoherence) : 'N/A'}</td>
  <td class="${colorClass(r.pathwayCoherence)}">${r.pathwayCoherence >= 0 ? pct(r.pathwayCoherence) : 'N/A'}</td>
  <td class="${colorClass(r.complexCoherence)}">${r.complexCoherence >= 0 ? pct(r.complexCoherence) : 'N/A'}</td>
  <td class="${r.consistent ? 'good' : 'bad'}">${r.consistent ? 'PASS' : 'FAIL'}</td>
  <td>${fmt2(r.meanIC)}</td>
  <td class="${colorClass(r.compositeScore)}">${fmt3(r.compositeScore)}</td>
</tr>"""}.join('\n')}
</table>

<footer>Generated by GSPA v0.1.0</footer>
</div>
</body>
</html>"""
    }

    private static String scoreCard(String label, double value, String detail) {
        def cls = colorClass(value)
        """<div class="card ${cls}">
    <div class="card-value">${value >= 0 ? pct(value) : 'N/A'}</div>
    <div class="card-label">${esc(label)}</div>
    <div class="card-detail">${esc(detail)}</div>
  </div>"""
    }

    private static String colorClass(double value) {
        if (value < 0) return ''
        if (value >= 0.9) return 'good'
        if (value >= 0.7) return 'ok'
        if (value >= 0.5) return 'warn'
        return 'bad'
    }

    private static String pct(double v) { String.format('%.1f%%', v * 100) }
    private static String fmt2(double v) { String.format('%.2f', v) }
    private static String fmt3(double v) { String.format('%.3f', v) }
    private static String esc(String s) { s?.replaceAll('&', '&amp;')?.replaceAll('<', '&lt;')?.replaceAll('>', '&gt;') ?: '' }

    private static String css() {
        '''\
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
       background: #f5f5f5; color: #333; line-height: 1.6; }
.container { max-width: 1000px; margin: 2rem auto; padding: 0 1rem; }
h1 { margin-bottom: 0.25rem; }
h2 { margin: 2rem 0 1rem; border-bottom: 2px solid #ddd; padding-bottom: 0.5rem; }
h3 { margin: 1rem 0 0.5rem; }
.subtitle { color: #666; margin-bottom: 1.5rem; }
.summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; margin: 1.5rem 0; }
.card { background: #fff; border-radius: 8px; padding: 1rem; text-align: center;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1); border-left: 4px solid #ccc; }
.card-value { font-size: 1.5rem; font-weight: 700; }
.card-label { font-size: 0.85rem; color: #666; margin-top: 0.25rem; }
.card-detail { font-size: 0.75rem; color: #999; margin-top: 0.25rem; }
.good { border-left-color: #2ecc71; } .good .card-value { color: #27ae60; }
.ok { border-left-color: #f39c12; } .ok .card-value { color: #e67e22; }
.warn { border-left-color: #e67e22; } .warn .card-value { color: #d35400; }
.bad { border-left-color: #e74c3c; } .bad .card-value { color: #c0392b; }
table { width: 100%; border-collapse: collapse; margin: 1rem 0; background: #fff;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
th, td { padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid #eee; }
th { background: #fafafa; font-weight: 600; font-size: 0.85rem; text-transform: uppercase; color: #666; }
td.good { color: #27ae60; font-weight: 600; }
td.ok { color: #e67e22; }
td.warn { color: #d35400; }
td.bad { color: #c0392b; font-weight: 600; }
p.ok { color: #27ae60; font-weight: 600; }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #ddd;
         font-size: 0.8rem; color: #999; text-align: center; }'''
    }
}
